### ISSUE TITLE
ms_simplify: R abort session

### ISSUE THREAD

**Issue by amaioran** [ateucher/rmapshaper#101]
Hi,
when executing the following code, the R session aborts:
  library("sf")
  library("rmapshaper")
  gadm.eu.nuts3 <- read_sf("gadm36_NUTS3_EU+.shp")
  gadm.eu.nuts3.simpl <- ms_simplify(gadm.eu.nuts3)

Originally I tried to open the shapefile using readOGR (rgdal package). I saw that someone had the same issue in the past so I tried with read_sf, but I get the same error
Maybe the problem is in the original shapefile? The shapefile is a shp that I created from the original GADM map and including only EU countries.

I tried to send you a compressed folder inlcuding the shapefile but the compressed file is >10MB (around 60MB). Any other way to send it to you for reproducibility?

Thank you in advance!
kind regards

Andrea

**Comment by ateucher** [comment]
HI @amaioran, similar to #83, you might try using the system mapshaper, so the processing is done outside of R.  It will require installing `node` on your system if you don't already have it (https://nodejs.org/en/), then installing the `mapshaper` library. Instructions are here: https://github.com/ateucher/rmapshaper#using-the-system-mapshaper.

Then you you can run `ms_simplify(gadm.eu.nuts3, sys = TRUE)`. If that doesn't work, please let me know.

**Comment by amaioran** [comment]
Hi @ateucher! thanks for your quick reply! I will try on my personal machine as soon as I can... unfortunately on my work machine this is difficult due to internal security policy reasons.... I could wait thousand of years before they accept to do it ;)

Thank you again: I will let you know!
Andrea

**Comment by ateucher** [comment]
@amaioran I'm going to close this, but if it is still an issue please go ahead and re-open it.
