### ISSUE TITLE
upcoming sf breaks rmapshaper on CRAN

### ISSUE THREAD

**Issue by edzer** [ateucher/rmapshaper#103]
See
* https://www.r-spatial.org/r/2020/03/17/wkt.html
* https://win-builder.r-project.org/incoming_pretest/sf_0.9-0_20200319_213604/reverseDependencies/summary.txt

Please update and submit to CRAN; let me know if you need help.

**Comment by ateucher** [comment]
Ok, thanks. Will look ASAP

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ateucher** [comment]
Well, after a single commit to fix the issue, and at least a day getting github actions working to actually check it with various GDAL/PROJ versions on all platforms, I think rmapshaper is good to go. Would you recommend waiting until sf is updated on CRAN or going now?

**Comment by edzer** [comment]
Yes. 

@etiennebr may want to check out Andy's github actions work.

**Comment by ateucher** [comment]
Sorry, was that "Yes" to waiting for sf?

**Comment by edzer** [comment]
eh, yes. On second thought: no need to wait.

**Comment by ateucher** [comment]
Perfect, thanks!

**Comment by ateucher** [comment]
rmapshaper 0.4.4 on CRAN now, passing all checks so far: https://cran.r-project.org/web/checks/check_results_rmapshaper.html
