### ISSUE TITLE
mapshaper cannot find geojson file (username with spaces?)

### ISSUE THREAD

**Issue by grcolli** [ateucher/rmapshaper#107]
> shape_municipios_simp <- rmapshaper::ms_simplify(shape_municipios, sys = T)
Error: [o] Command expects a single value. Received: C:\Users\Guarino R. Colli\AppData\Local\Temp\RtmpScK7dh\file41301ed349d8.geojson
Run mapshaper -h to view help
Error: Cannot open "C:\Users\Guarino R. Colli\AppData\Local\Temp\RtmpScK7dh\file41301ed349d8.geojson"; The file doesn't seem to exist.

From other forums, the issue is related to a username (and directory names) with spaces. Is there a way around this, other than creating a new user? Thanks, Guarino.

> Sys.getenv()
ALLUSERSPROFILE                          C:\ProgramData
APPDATA                                  C:\Users\Guarino R. Colli\AppData\Roaming
ChocolateyInstall                        C:\ProgramData\chocolatey
ChocolateyLastPathUpdate                 132333295157412892
CLICOLOR_FORCE                           1
CLIENTNAME                               leptophis
CommonProgramFiles                       C:\Program Files\Common Files
CommonProgramFiles(x86)                  C:\Program Files (x86)\Common Files
CommonProgramW6432                       C:\Program Files\Common Files
COMPUTERNAME                             TYRANNOSAURUS
ComSpec                                  C:\WINDOWS\system32\cmd.exe
DISPLAY                                  :0
DriverData                               C:\Windows\System32\Drivers\DriverData
GDAL_DATA                                C:/Users/Guarino R. Colli/Documents/R/win-library/4.0/sf/gdal
GFORTRAN_STDERR_UNIT                     -1
GFORTRAN_STDOUT_UNIT                     -1
HOME                                     C:\Users\Guarino R. Colli\Documents
HOMEDRIVE                                C:
HOMEPATH                                 \Users\Guarino R. Colli
LOCALAPPDATA                             C:\Users\Guarino R. Colli\AppData\Local
LOGONSERVER                              \\TYRANNOSAURUS
MPLENGINE                                tkAgg
MSYS2_ENV_CONV_EXCL                      R_ARCH
NUMBER_OF_PROCESSORS                     44
OneDrive                                 C:\Users\Guarino R. Colli\OneDrive - unb.br
OneDriveCommercial                       C:\Users\Guarino R. Colli\OneDrive - unb.br
OS                                       Windows_NT
tools40\usr\bin;C:\Program               C:
                                         Files\R\R-4.0.0\bin\x64;C:\Python38\Scripts\;C:\Python38\;C:\Program Files
                                         (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS
                                         Client\;C:\Program Files\Intel\iCLS
                                         Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program
                                         Files\Dell\Dell Data Protection\Drivers\TSS\bin\;C:\Program Files
                                         (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
                                         Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
                                         (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                                         Files\Intel\Intel(R) Management Engine
                                         Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\MiKTeX
                                         2.9\miktex\bin\x64\;C:\Program
                                         Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\Guarino R.
                                         Colli\AppData\Local\Microsoft\WindowsApps;C:\Users\Guarino R.
                                         Colli\AppData\Local\GitHubDesktop\bin;C:\Users\Guarino R.
                                         Colli\AppData\Local\Microsoft\WindowsApps;C:\Users\Guarino R.
                                         Colli\AppData\Roaming\npm
PATHEXT                                  .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
PROCESSOR_ARCHITECTURE                   AMD64
PROCESSOR_IDENTIFIER                     Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
PROCESSOR_LEVEL                          6
PROCESSOR_REVISION                       4f01
ProgramData                              C:\ProgramData
ProgramFiles                             C:\Program Files
ProgramFiles(x86)                        C:\Program Files (x86)
ProgramW6432                             C:\Program Files
PROJ_LIB                                 C:/Users/Guarino R. Colli/Documents/R/win-library/4.0/sf/proj
PSModulePath                             C:\Program
                                         Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC                                   C:\Users\Public
QT_D3DCREATE_MULTITHREADED               1
R_ARCH                                   /x64
R_COMPILED_BY                            gcc 8.3.0
R_DOC_DIR                                C:/PROGRA~1/R/R-4.0.0/doc
R_HOME                                   C:/PROGRA~1/R/R-4.0.0
R_LIBS_USER                              C:/Users/Guarino R. Colli/Documents/R/win-library/4.0
R_USER                                   C:/Users/Guarino R. Colli/Documents
RMARKDOWN_MATHJAX_PATH                   C:/Program Files/RStudio/resources/mathjax-26
RS_LOCAL_PEER                            \\.\pipe\10135-rsession
RS_RPOSTBACK_PATH                        C:/Program Files/RStudio/bin/rpostback
RS_SHARED_SECRET                         63341846741
RSTUDIO                                  1
RSTUDIO_CONSOLE_COLOR                    256
RSTUDIO_CONSOLE_WIDTH                    80
RSTUDIO_MSYS_SSH                         C:/Program Files/RStudio/bin/msys-ssh-1000-18
RSTUDIO_PANDOC                           C:/Program Files/RStudio/bin/pandoc
RSTUDIO_SESSION_PORT                     10135
RSTUDIO_USER_IDENTITY                    Guarino R. Colli
RSTUDIO_WINUTILS                         C:/Program Files/RStudio/bin/winutils
RTOOLS40_HOME                            C:\rtools40
SESSIONNAME                              RDP-Tcp#4
SystemDrive                              C:
SystemRoot                               C:\WINDOWS
TEMP                                     C:\Users\Guarino R. Colli\AppData\Local\Temp
TERM                                     xterm-256color
TMP                                      C:\Users\Guarino R. Colli\AppData\Local\Temp
TZDIR                                    C:/PROGRA~1/R/R-4.0.0/share/zoneinfo
USERDOMAIN                               TYRANNOSAURUS
USERDOMAIN_ROAMINGPROFILE                TYRANNOSAURUS
USERNAME                                 Guarino R. Colli
USERPROFILE                              C:\Users\Guarino R. Colli
windir                                   C:\WINDOWS

**Comment by ateucher** [comment]
@grcolli thanks very much for this report. I think I've fixed it, if you get a chance can you please try out the development version by installing from here:

```r
# install.packages("remotes")
remotes::install_github("ateucher/rmapshaper")
library(rmapshaper)
```

**Comment by grcolli** [comment]
Hi Andy, thanks a lot for your prompt response. I reran the code but apparently the issue was not solve (see below). I'm ready to help and provide any additional info deemed necessary. Cheers, G.

> remove(list = ls())
> # Load packages
> library(iterators)
> library(magrittr)
> setwd("~/GitHub/COVID-19")
> # Make sure working directory has been correctly set before running this!
> my.dir <- paste(getwd(), "/", sep = "")
> # Load shape files
> shape_municipios <- 
+   rgdal::readOGR(paste(my.dir, "data/shape_municipios/BRMUE250GC_SIR.shp", sep = ""),
+                  stringsAsFactors = F)
OGR data source with driver: ESRI Shapefile 
Source: "C:\Users\Guarino R. Colli\Documents\GitHub\COVID-19\data\shape_municipios\BRMUE250GC_SIR.shp", layer: "BRMUE250GC_SIR"
with 5572 features
It has 2 fields
> # Simplify shape files with rmapshaper
> # Make sure mapshaper is installed in system
> shape_municipios_simp <- rmapshaper::ms_simplify(shape_municipios, sys = T)
Error: [o] Command expects a single value. Received: C:\Users\Guarino R. Colli\AppData\Local\Temp\RtmpeAV1bp\file5cd4186c1b71.geojson
Run mapshaper -h to view help
Error: Cannot open "C:\Users\Guarino R. Colli\AppData\Local\Temp\RtmpeAV1bp\file5cd4186c1b71.geojson"; The file doesn't seem to exist.

**Comment by grcolli** [comment]
Andy,
my bad. After installing the development version of rmapshaper, the code ran smoothly! Thanks a lot. Best, G.

> # Simplify shape files with rmapshaper
> # Make sure mapshaper is installed in system
> shape_municipios_simp <- rmapshaper::ms_simplify(shape_municipios, sys = T)
[i] Snapped 40638 points
[simplify] Repaired 23 intersections
[filter] Retained 5,572 of 5,572 features
[o] Wrote C:\Users\Guarino R. Colli\AppData\Local\Temp\RtmpkhLjym\file62482e77698e.geojson

**Comment by ateucher** [comment]
Oh excellent! I was scratching my head, as I was sure my patch would fix it. Thanks for trying again and reporting back

**Comment by ateucher** [comment]
One more unrelated though @grcolli - it's generally a bit risky to post the output of `Sys.getenv()` as many people store sensitive info such as authorization tokens there.

**Comment by grcolli** [comment]
Thanks Andy. Will be more careful next time!







***ATENÇÃO***ATTENTION***
Não use o endereço grcolli@unb.br; ao invés, use grcolli@icloud.com
Do not use the address grcolli@unb.br; instead, use grcolli@icloud.com



*******************************************
Prof. Guarino R. Colli
Departamento de Zoologia
Universidade de Brasília
70910-900 Brasília, DF  BRASIL
Phone: +55-61-3107-3013 – +55-61-3107-3036
e-mail: grcolli@icloud.com
Skype: grcolli
ResearcherID: http://www.researcherid.com/rid/A-5368-2008
ORCID ID: https://orcid.org/0000-0002-2628-5652
Lattes CV:  http://lattes.cnpq.br/2272000258230548


"What would you think if I sang out of tune?
Would you stand up and walk out on me?
Lend me your ears and I'll sing you a song
And I'll try not to sing out of key

Oh, I get by with a little help from my friends
Mm, I get high with a little help from my friends
Mm, gonna try with a little help from my friends"
(Lennon & McCartney, 1967)
