### ISSUE TITLE
System mapshaper not detectable in R

### ISSUE THREAD

**Issue by JWusagi** [ateucher/rmapshaper#109]
Hi there

I'm trying to use the rmapshaper_0.4.4 to simplify a large spatial file in order to upload it onto a shinyApp.  It contains boundaries of all 32,844 LSOAs in England (LSOA is one geographical unit consisting around 1,500 residents).  Having tried with the ms_simplify and R session aborted, I think I should grab the system mapshaper by the command "sys=TRUE" as the file is quite large: 

object.size(lsoa.bound_T)
657069488 bytes

I have followed all steps in https://cran.r-project.org/web/packages/rmapshaper/vignettes/rmapshaper.html to download node and used npm install -g mapshaper to install it via the Terminal.  And I can confirm they should be properly installed, as I can check their versions in Terminal: 

![image](https://user-images.githubusercontent.com/81804762/113404613-5b417900-93a0-11eb-991f-fb8e69de4f6c.png)

However when I'm checking the existence of mapshaper in R by check_sys_mapshaper(), I still get the same ERROR message as I did before installing node and mapshaper: 

![image](https://user-images.githubusercontent.com/81804762/113404743-8deb7180-93a0-11eb-8bdd-1de719797f5a.png)

I'm wondering how does R pick up the mapshaper installed in node from R's PATH?  I know it might goes beyond what does the rmapshaper do, and relates to some knowledge about managing packages and paths on computer.  But I'm wondering if anyone is able to provide some tips, or anyone has experienced something similar? 

Many thanks,
Jie

**Comment by ateucher** [comment]
Hi @JWusagi,

Can you please run the following in your Terminal:

```
which mapshaper
echo $PATH
```

And this in your R session:

```r
Sys.which("mapshaper")
Sys.getenv("PATH")
```

And post the results here?

**Comment by JWusagi** [comment]
> Hi @JWusagi,
> 
> Can you please run the following in your Terminal:
> 
> ```
> which mapshaper
> echo $PATH
> ```
> 
> And this in your R session:
> 
> ```r
> Sys.which("mapshaper")
> Sys.getenv("PATH")
> ```
> 
> And post the results here?


Hi Andy

Thanks very much for your reply.  Please see the screenshots in terminal and R session below: 

Terminal: 
![image](https://user-images.githubusercontent.com/81804762/113493439-34d22980-94d7-11eb-8a51-d24f786248cb.png)

R: 
![image](https://user-images.githubusercontent.com/81804762/113493447-47e4f980-94d7-11eb-937c-5ce8687e7a68.png)

**Comment by ateucher** [comment]
Hi @JWusagi - you're correct, this isn't an `rmapshaper` issue per se, rather that R doesn't always pick up environment variables (such as `PATH`) set elsewhere (such as `~/.profile`, `~./bashrc` etc). 

You can add to the `PATH` by editing your `.Renviron` file (usually at `~/.Renviron`). The easiest way to find and edit it is with `usethis::edit_r_environ()`. Then add the following line to the file:

```
PATH=/Users/JWusagi/.npm-global/bin/:$PATH
```

Alternatively, I think you can change where npm packages are installed to (or at least symlinked to) with something like:

```
npm config set prefix /usr/local
```

which should symlink your global npm packages to `/usr/local/bin` which _is_ on `PATH` in R. You may need to reinstall mapshaper, though I'm not 100% sure.

**Comment by JWusagi** [comment]
> Hi @JWusagi - you're correct, this isn't an `rmapshaper` issue per se, rather that R doesn't always pick up environment variables (such as `PATH`) set elsewhere (such as `~/.profile`, `~./bashrc` etc).
> 
> You can add to the `PATH` by editing your `.Renviron` file (usually at `~/.Renviron`). The easiest way to find and edit it is with `usethis::edit_r_environ()`. Then add the following line to the file:
> 
> ```
> PATH=/Users/JWusagi/.npm-global/bin/:$PATH
> ```
> 
> Alternatively, I think you can change where npm packages are installed to (or at least symlinked to) with something like:
> 
> ```
> npm config set prefix /usr/local
> ```
> 
> which should symlink your global npm packages to `/usr/local/bin` which _is_ on your `PATH` in R. You may need to reinstall mapshaper, though I'm not 100% sure.

Hi @ateucher 

Thanks so much - it works perfectly!  I tried out your first suggestion and the system mapshaper perfectly gets engaged for large files.  I'll close this issue then if you are happy? 

Thanks again,
Jie

**Comment by ateucher** [comment]
Great, thanks for reporting back!
