### ISSUE TITLE
Expose `-quiet` flag?

### ISSUE THREAD

**Issue by dblodgett-usgs** [ateucher/rmapshaper#125]
I'm finding it impossible to suppress messages when calling rmapshaper with sys=TRUE

Those are some strong messages!! Any idea how to suppress these? Would it need to be the `-quiet` flag?

```r
nc <- sf::read_sf(system.file("gpkg/nc.gpkg", package = "sf"))

sink(file = tempfile())
suppressMessages(suppressWarnings({
  output <- capture.output({
    o <- rmapshaper::ms_explode(nc, sys = TRUE)
  })
}))
sink()
```

![image](https://user-images.githubusercontent.com/1492803/168720701-13f33c7c-f978-4a4c-9969-f75fb94bb458.png)

**Comment by ateucher** [comment]
Good idea!
