### ISSUE TITLE
Vulnerability to absence of retiring r-spatial packages

### ISSUE THREAD

**Issue by rsbivand** [ateucher/rmapshaper#129]
[00check.log](https://github.com/ateucher/rmapshaper/files/11141248/00check.log)
is a recent check log from running under `_SP_EVOLUTION_STATUS_=2` without retiring r-spatial packages (suggested in this package) on the library path. The minimal correction is to check that the package namespaces can be loaded, and if not, do not run those parts of the examples. It would be safer in the longer term to replace retiring r-spatial packages with active r-spatial/rspatial packages (see https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html).

**Comment by rsbivand** [comment]
Thanks, 0.5.0 CMD check in a scenario using sp evolution status 2 (substitute use of rgdal with sf for projection/transformation/CRS) and absence of retiring packages from the library path gives this log:
[00check.log](https://github.com/ateucher/rmapshaper/files/11352622/00check.log)

**Comment by ateucher** [comment]
Great, thanks for reporting back
