### ISSUE TITLE
ms_simplify fails on CentOs redhat - unexpected token .

### ISSUE THREAD

**Issue by B-Nilson** [ateucher/rmapshaper#165]
I use ms_simplify(poly, weighting = 1, keep_shapes=T) to simplify polygons read in by rgdal::readOGR. On my windows machine this works fine, but on our web server (centos redhat server) I get an error that seems to be related to parsing the "mapshaper/mapshaper-browserify.min.js" file. 

`SyntaxError: Unexpected token ."`

![image](https://github.com/ateucher/rmapshaper/assets/45985474/449a0b66-5eaf-47b0-bd42-d8093086d802)

Here is the output of `version` for our linux server:
![image](https://github.com/ateucher/rmapshaper/assets/45985474/442988f1-b73b-4694-894b-c2829f2c29fe)

Happy to add anymore information as necessary

**Comment by ateucher** [comment]
This is a duplicate of #157 - I hope you found a solution there @B-Nilson!
