### ISSUE TITLE
Preventing deletion of polygons

### ISSUE THREAD

**Issue by ericvmai** [ateucher/rmapshaper#166]
I have a large geojson that is needing to be simplified with a keep of 0.1. However, when doing this, I lose three polygons in the process. Is there any way to prevent polygon loss while still simplifying the other polygons?

I have to increase the keep to 0.38 to maintain the three polygons that are lost.

**Comment by ateucher** [comment]
There is a `keep_shapes` argument in `ms_simplify()`. Have you tried setting that to `TRUE`? https://andyteucher.ca/rmapshaper/reference/ms_simplify.html

**Comment by ericvmai** [comment]
totally my fault for not seeing that as an option. works great! Thanks again for creating this.
