### ISSUE TITLE
Imports?

### ISSUE THREAD

**Issue by sckott** [ateucher/rmapshaper#17]
noticed that in your `NAMESPACE` there's no import statements. Looks like you namespace imported function calls in your pkg, which is i think why check doesn't complain. I'd add `@importFrom ...` to https://github.com/ateucher/rmapshaper/blob/master/R/rmapshaper.R

or is there a good reason no to?

**Comment by ateucher** [comment]
I've been a bit confused about this for a time, but after re-reading the [imports](http://r-pkgs.had.co.nz/namespace.html#imports) section in r-pkgs again, I think this is ok. In fact, it is what Hadley recommends.  I've always used `@importFrom` before, but I actually liked writing using `::` throughout. It keeps it clear in my head what functions I'm using from where...

**Comment by sckott** [comment]
okay, hadn't read that section
