### ISSUE TITLE
Calling ms_simplify returns Syntax Error: Unexpected token

### ISSUE THREAD

**Issue by Earlien** [ateucher/rmapshaper#171]
Calling ms_simplify returns "Error: SyntaxError: Unexpected token  ." every time its called.  This is true of my sf objects and both examples (geojson and sf) in the R help file for any value of `keep`.  Tested on both Linux and Windows 10.

**Comment by ateucher** [comment]
Hi, this is a duplicate of #157. You your version of `V8` needs to be built with libv8 version >= 8.1.307.30. For windows you should be fine installing the binary version v8; on Linux follow the directions [here](https://github.com/jeroen/V8).
