### ISSUE TITLE
ms_simplify returns error: "Error: SyntaxError: Unexpected token ."

### ISSUE THREAD

**Issue by cortexR** [ateucher/rmapshaper#174]
The error even appears when running the example in the README:

> file <- system.file("gpkg/nc.gpkg", package = "sf")
> nc_sf <- read_sf(file)
> nc_simp <- ms_simplify(nc_sf)

Returns:
> Error: SyntaxError: Unexpected token .

**Comment by ateucher** [comment]
Hi, are you getting a warning when you do `library(rmapshaper)` about an old version of the v8 library?

I think you also posted in the [rOpensci forum](https://discuss.ropensci.org/t/warning-message-for-v8-package-this-system-has-a-very-old-version-of-libv8/3759/3?u=andy_teucher), where I've left a reply. I'll repost it here, let me know if that helps. 

---

Usually just reinstalling the V8 R package should be enough, as @jeroen has done a lot of work lately to ensure that installations are built with a new enough version of v8. If you are on Windows or Mac and installing the binary version of the V8 R package (`install.packages("V8", type = "binary")`), it will be be built with an up-to-date version of v8 and you should be fine. If you are on [Linux or need to install from source on MacOS](https://github.com/jeroen/V8?tab=readme-ov-file#linux-static-libv8), you should set the `DOWNLOAD_STATIC_LIBV8` environment variable before installing it:

```r
Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
install.packages("V8")
```

There may reasons be why that is not possible on your system, in which case the V8 R package will be built with whatever version of the v8 library is available on your system. The [V8 installation instructions](https://github.com/jeroen/V8?tab=readme-ov-file#linux-static-libv8) should help give you guidance on updating the v8 library on many operating systems.

**Comment by cortexR** [comment]
Thanks. 
No warning about old version of v8 when loading package rmapshaper, but another warning:

> > library(rmapshaper)
> The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
> which was just loaded, will retire in October 2023.
> Please refer to R-spatial evolution reports for details, especially
> https://r-spatial.org/r/2023/05/15/evolution4.html.
> It may be desirable to make the sf package available;
> package maintainers should consider adding sf to Suggests:.
> The sp package is now running under evolution status 2
>      (status 2 uses the sf package in place of rgdal)


However, loading V8 returns this warning:

> > library(V8)
> Using V8 engine 6.2.414.50
> Warning message:
> package ‘V8’ was built under R version 4.1.3 

R version I use is  "R version 4.1.1 (2021-08-10)". Could that be the issue?

Package version I use seems to be the latest:

```
> packageVersion("rmapshaper")
[1] ‘0.5.0’
```

**Comment by jeroen** [comment]
That version of R is very old, and it has an old libv8. The current version of R is 4.4.x. Your problem will be fixed if you upgrade.
