### ISSUE TITLE
geojsonio cran

### ISSUE THREAD

**Issue by sckott** [ateucher/rmapshaper#18]
should we push new version of `geojsonio` to CRAN soon? that is, are you trying to push this soon?

**Comment by ateucher** [comment]
I think I'm going to add more mapshaper commands (See #12) before I push to CRAN. It will be my first attempt at submitting to CRAN, so I will take some time to make sure I've got my t's crossed and i's dotted... Hopefully in the next week or so though.

**Comment by sckott** [comment]
okay, still no response on the osx binaries of `rgdal`, soooooo

**Comment by ateucher** [comment]
Ugh. I would suggest pushing and leave it to CRAN to sort out - but up to you of course. 

But first, I think #16 might have implications for `geojsonio` as well, so I'm going to look at it today and try to PR something to you. I think there is a case for `MultiPointDataFrame` methods in `geojson_json`, `geojson_list`, `geojson_read`, `geojson_write`, etc.

**Comment by sckott** [comment]
> Ugh. I would suggest pushing and leave it to CRAN to sort out - but up to you of course.

right, but i worry about osx users though. if we require `rgdal > X version` they have to install from source, and I don't know if that will end up well or not

> But first, I think #16 might have implications for geojsonio as well, so I'm going to look at it today and try to PR something to you

sounds good.

**Comment by ateucher** [comment]
@sckott I've continued this back in the relevant [geojsonio issue](https://github.com/ropensci/geojsonio/issues/69#issuecomment-159709466)

**Comment by sckott** [comment]
thanks

**Comment by ateucher** [comment]
With regards to `SpatialMultiPointDataFrame` methods in `geojsonio`, I think I'll hold off. I was poking around in the `sp` r-forge repository and it looks like they're newly added classes that they are still working on implementing methods for. I think it's best to wait and see...

**Comment by sckott** [comment]
Okay, thanks for update

**Comment by ateucher** [comment]
geojsonio 0.1.6 pushed to CRAN on 2016-01-15
