### ISSUE TITLE
Use V8

### ISSUE THREAD

**Issue by ateucher** [ateucher/rmapshaper#2]
I'd like to include the mapshaper javascript library and use [V8](https://cran.r-project.org/web/packages/V8/index.html), so that users don't have to have `node.js` and the `mapshaper` module installed. Also, using `system()` calls to use mapshaper commands in node is very inefficient due to all of the disk i/o required.

I've started trying in `test_v8.R` in the [test-v8](https://github.com/ateucher/rmapshaper/tree/test-v8) branch.  Unfortunately I'm a total javascript hack.

I've got the library imported, and a basic call to `mapshaper.applyCommands` running with no errors (as documented [here](https://github.com/mbloch/mapshaper/wiki/Using-mapshaper-programmatically))- but it doesn't return anything. I've run through most of the javascript call stack with a bunch of `console.log()`'s and I think it dies with the call to [`utils.reduceAsync`](https://github.com/ateucher/rmapshaper/blob/test-v8/inst/mapshaper/mapshaper.js#L15349) [here](https://github.com/ateucher/rmapshaper/blob/test-v8/inst/mapshaper/mapshaper.js#L15311).

V8 doesn't ship with some things that Node has, such as the timer functions `setImmediate` and `setTimout`, so I was initially getting the errors `ReferenceError: setTimeout is not defined` and `ReferenceError: setImmediate is not defined`. After some googling around, I found some versions of these functions that people had put together, and included them - it stopped the errors, but now `mapshaper.applyCommands` just fails silently.  I have a strong suspicion that the totally hacky way I did this is the source of the problem.

If anyone has any ideas - either by telling I'm totally off-track, or by telling me how I might include the timers properly, I would be really grateful.

@sckott, @timelyportfolio - do you have any ideas?

**Comment by sckott** [comment]
you're referring to the `test_v8.R`, right?

**Comment by ateucher** [comment]
Tep

**Comment by ateucher** [comment]
Yep (autocorrect only works when you don't want it to)

**Comment by ateucher** [comment]
In `inst/ ` - sorry, forgot to specify that

**Comment by sckott** [comment]
`mapshaper.js` is from https://github.com/mbloch/mapshaper/blob/master/mapshaper.js or did you browserify to get that?

**Comment by ateucher** [comment]
It is that one, yes, though I have tried with browserify and got the same result. I think because browsers have `setTimeout` built in as well, they aren't included when you browserify

**Comment by sckott** [comment]
have you tried in node REPL yet?  curious what that looks like

**Comment by ateucher** [comment]
No, I haven't actually. Good call - I'll give it a try

**Comment by ateucher** [comment]
In the node REPL:
(first need to install mapshaper with `npm install mapshaper`)

```javascript
> var mapshaper = require('mapshaper');
> var poly = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [-114.345703125, 39.4369879],
            [-116.4534998, 37.18979823791],
            [-118.4534998, 38.17698709],
            [-115.345703125, 43.576878],
            [-106.611328125, 43.4529188935547],
            [-105.092834092, 46.20938402],
            [-106.66859, 39.4389646],
            [-103.6117867, 36.436756],
            [-114.34579879, 39.4361929]
          ]
        ]
      },
      "properties": {}
    }
  ]
}

> mapshaper.applyCommands('-simplify 0.4 visvalingam', poly, function(err, data) {
   if (err) console.error(err);
   console.log(data); // did this instead of return just so it prints in the console
})

{"type":"GeometryCollection","geometries":[{"type":"Polygon","coordinates":[[[-114.345703125,39.4369879],[-115.345703125,43.576878],[-106.611328125,43.4529188935547],[-103.6117867,36.436756],[-114.34579879,39.4361929]]]}]}
```
It returns a simplified GeoJSON object (5 vertices vs original 9), so it is working there...

**Comment by timelyportfolio** [comment]
I'm having a look now.  Working with the reduced `V8` set can be very tricky.

**Comment by timelyportfolio** [comment]
The issue is `setTimeout` does not exist in `V8`, so this [line](https://github.com/mbloch/mapshaper/blob/master/src/cli/mapshaper-commands.js#L160) fails.  I don't think there is a clean workaround for the lack of `setTimeout`, so instead of `applyCommands`, the best solution will probably be to do the unrecommended [method 4](https://github.com/mbloch/mapshaper/wiki/Using-mapshaper-programmatically#option-four-call-individual-functions-for-each-command).

**Comment by ateucher** [comment]
Thanks - I was thinking that might be the route. Might be painful, but I'll start exploring :)

**Comment by timelyportfolio** [comment]
Hope to have some code shortly as basic example.

**Comment by sckott** [comment]
glad @timelyportfolio is here, i didn't have any ideas :smile:

**Comment by ateucher** [comment]
Ditto! Thanks @timelyportfolio - If you don't have time to work up an example, I'm pretty sure I can fumble my way through (though of course if you do, that would be fantastic)

**Comment by timelyportfolio** [comment]
Took me a little longer since I've been lazy and using the UI.  I'm not familiar with the command-line options.  Here is what I have for now.  I'll post it up in its ugly state since I have to turn off the computer for the day.

It is all in the fork https://github.com/timelyportfolio/rmapshaper/tree/V8 with code [here](https://github.com/timelyportfolio/rmapshaper/blob/V8/inst/examples/experiment_V8.R).  Hope it helps.  I'll be able to get back on it in the morning or tomorrow night.

**Comment by ateucher** [comment]
This is great! Thank you so much - I'm going to try to see if I can play with it tonight

**Comment by timelyportfolio** [comment]
changed the above ref code to an anonymous function to return the data. I'll try to work through some of the other commands to get a better sense of reusability and patterns.

**Comment by ateucher** [comment]
This is working nicely, thank you so very much! I don't think you need to browserify, I'm using this one here: https://github.com/mbloch/mapshaper/blob/master/mapshaper.js and it works just the same - is there a reason to browserify?

As `mapshaper.runCommand` returns a dataset with arcs etc (presuming this is an internal format?), I poached a few lines from `Mapshaper.processFileContent` to grab output options, which are then passed on to `internal.exportFileContent` along with the dataset to convert back to geojson for the output. Example is below - do you have any thoughts?

```
## Most of this code courtesy of Kent Russell (GitHub: @timelyportfolio;
## twitter: @klr)
library(V8)

# get a place to work
ctx <- new_context()

# source mapshaper.js (which is from
# https://github.com/mbloch/mapshaper/blob/master/mapshaper.js)
ctx$source('./inst/mapshaper/mapshaper.js')

# check to make sure mapshaper is there
# ctx$get('Object.keys(mapshaper)')

# run the example from issue #2
ctx$eval(
  'var poly = {
  "type": "FeatureCollection",
  "features": [
  {
  "type": "Feature",
  "geometry": {
  "type": "Polygon",
  "coordinates": [
  [
  [-114.345703125, 39.4369879],
  [-116.4534998, 37.18979823791],
  [-118.4534998, 38.17698709],
  [-115.345703125, 43.576878],
  [-106.611328125, 43.4529188935547],
  [-105.092834092, 46.20938402],
  [-106.66859, 39.4389646],
  [-103.6117867, 36.436756],
  [-114.34579879, 39.4361929]
  ]
  ]
  },
  "properties": {"id":"foobar"}
  }
  ]
  }
  '
)

# see if poly is there
# ctx$get('poly')

# set commands
ctx$eval('var command = mapshaper.internal.parseCommands("-simplify 0.4 visvalingam")')

# to set can do something ugly like this
out <- ctx$get(
"
(function(){
  var return_data = {};
  mapshaper.runCommand(
    command[0],
    mapshaper.internal.importFileContent(poly, null, {}),
    function(err,data){
      // This chunk from Mapshaper.ProcessFileContent to get output options:
      // if last command is -o, use -o options for exporting
      outCmd = command[command.length-1];
      if (outCmd && outCmd.name == 'o') {
        outOpts = command.pop().options;
      } else {
        outOpts = {};
      }
      // Convert dataset to geojson for export
      // (or if other format supplied in output options)
      return_data = mapshaper.internal.exportFileContent(data, outOpts);
    }
  )
return return_data;
})()
"
)

out[[1]]
[1] "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"properties\":{\"id\":\"foobar\"},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-114.345703125,39.4369879],[-115.345703125,43.576878],[-106.611328125,43.4529188935547],[-103.6117867,36.436756],[-114.34579879,39.4361929]]]}}]}"
```

**Comment by ateucher** [comment]
Ok, the basis of a reusable base function here I think:

```r
library(V8)

ctx <- new_context()
ctx$source('./inst/mapshaper/mapshaper.js')

run_mapshaper_commands <- function(data, commands) {
  ctx$eval(paste0('var command = mapshaper.internal.parseCommands("',
                  commands, '")'))

  ctx$eval(paste0('var data = ', data))

  out <- ctx$get(
    "
    (function(){
      var return_data = {};
      mapshaper.runCommand(
        command[0],
        mapshaper.internal.importFileContent(data, null, {}),
        function(err,data){
          // This chunk from Mapshaper.ProcessFileContent to get output options:
          // if last command is -o, use -o options for exporting
          outCmd = command[command.length-1];
          if (outCmd && outCmd.name == 'o') {
            outOpts = command.pop().options;
          } else {
            outOpts = {};
          }
          // Convert dataset to geojson for export
          // (or if other format supplied in output options)
          return_data = mapshaper.internal.exportFileContent(data, outOpts);
        }
      )
    return return_data;
    })()
    "
  )

  out
}

poly <- '{
  "type": "FeatureCollection",
  "features": [
  {
  "type": "Feature",
  "geometry": {
  "type": "Polygon",
  "coordinates": [
  [
  [-114.345703125, 39.4369879],
  [-116.4534998, 37.18979823791],
  [-118.4534998, 38.17698709],
  [-115.345703125, 43.576878],
  [-106.611328125, 43.4529188935547],
  [-105.092834092, 46.20938402],
  [-106.66859, 39.4389646],
  [-103.6117867, 36.436756],
  [-114.34579879, 39.4361929]
  ]
  ]
  },
  "properties": {"id":"foobar"}
  }
  ]
  }'

run_mapshaper_commands(poly, "-simplify 0.4 visvalingam")

# content
# 1 {"type":"FeatureCollection","features":[{"type":"Feature","properties":{"id":"foobar"},"geometry":
# {"type":"Polygon","coordinates":[[[-114.345703125,39.4369879],[-115.345703125,43.576878],
# [-106.611328125,43.4529188935547],[-103.6117867,36.436756],[-114.34579879,39.4361929]]]}}]}
#     filename
# 1 layer1.json
```

**Comment by timelyportfolio** [comment]
So glad this was helpful, and very good call on `exportFileContent`.  I ran out of time before I got the chance to explore the export.  Here are my couple of comments on the reusable function.

1.  `run_mapshaper_commands` should probably be `run_mapshaper_command` since this is targeted toward a single command.  In the near future, I would like to see another `R` function to chain/pipe/reduce multiple commands like `applyCommands` from `mapshaper`.  We'll need to [add/borrow some more logic](https://github.com/mbloch/mapshaper/blob/master/src/cli/mapshaper-commands.js#L113-L125) to make this happen.

2.  documentation will be tougher than I first expected.  `mapshaper` is well-documented, so I thought we could leverage quite a bit, but I think the user who chooses `rmapshaper` over `mapshaper` will have a hard time translating from JS to R.

3.  do we know anyone that uses `mapshaper` + the R set of geo tools who can provide more insight on an integrated workflow all in `R`?  I think I mentioned I have mainly used the web gui, and my geo skills are only a hobby.

In terms of browserify/non-browserify, I'm not sure I know enough to discuss the advantages and disadvantages.  Eventually, once we get to a sort of real functioning package, it seems like it would be nice to have one minified/uglified bundle.  The bundle looks like it will be about 450kb when minified.  I'm also trying to consider how it might look if we merge the `htmlwidget`.  As of now, it seems like we will still need two js files, so I don't think that will affect the decision.

**Comment by timelyportfolio** [comment]
@ateucher as a side note, did you know mapshaper goes back to 2006 http://www.cartogis.org/docs/proceedings/2006/bloch_harrower.pdf?

**Comment by ateucher** [comment]
Wow, that's impressive that it's been around since 2006.  My main motivation for doing this is that there is no method in any R geo package that I know of that provides topologically-aware polygon simplification (which is what the Visvalingam method provides). I'm surprised that no one has done it before.

Thanks for these insights.

1. Good call on the function name. Yes, I've been thinking about that too - If a user wants to apply multiple commands to a dataset, it would be nice to avoid multiple independent trips into javascript land.

2. I wondered if there is a way to do that, but my javascipt skills aren't up to the challenge (whenever I run into async stuff I get a bit lost). Would just a rewrite of `utils.reduceAsync` (https://github.com/mbloch/mapshaper/blob/master/src/cli/mapshaper-commands.js#L159) do the job?

3. Agreed. My intent was to make the API more R-ish than JS-ish. See [here](https://github.com/ateucher/rmapshaper/blob/master/R/simplify.R) for an example of how I was planning on providing and documenting the single commands.

4. I sort of fit this bill, but have only used `mapshaper` cli faily lightly so far, and I wouldn't say I'm a geo expert but I'm relatively familiar with the main R geo packages. Another set of eyes would be great. I think there would be a lot of overlap between most of the `mapshaper` commands and functions in existing R packages, with the exception of `simplify` as I mentioned above.

**Comment by timelyportfolio** [comment]
We lose async, and I could easily be missing something, but changing reduceAsync as in these [lines](https://github.com/timelyportfolio/rmapshaper/blob/test-v8/inst/js/mapshaper/mapshaper.js#L15349-L15369) seems to give us the ability to use `mapshaper.applyCommands` again.  @ateucher could you test a little with a series of commands to see if it works with more than just the `simplify` test.

**Comment by ateucher** [comment]
Wow, that's it eh? Makes sense now that I look at it ;)  Nicely done - I'll try to give it a bash tomorrow.

**Comment by ateucher** [comment]
Ok, I've done a bit more testing with more complex data and commands using your clever fix to `reduceAsync`:

```r
library(V8)
library(geojsonio)

mapshaper <- "inst/mapshaper/mapshaper.js"
ms <- new_context()
ms$source(mapshaper)

geojson_file <- system.file("examples", "california.geojson", package = "geojsonio")
california <- geojson_read(geojson_file)
topojson_file <- system.file("examples", "us_states.topojson", package = "geojsonio")
us_states <- geojson_json(topojson_read(topojson_file))

ms$eval("var return_data;")

callback <- "function(Error, data) {
  if (Error) console.error(Error);
  return_data = data;
}"

# simplify
ms$call("mapshaper.applyCommands", "-simplify 0.05 visvalingam", california, JS(callback))
ms$get("return_data")

# simplify with snapping
ms$call("mapshaper.applyCommands", "snap -simplify 0.05", california, JS(callback))
ms$get("return_data")

# convert to points (centroid)
ms$call("mapshaper.applyCommands", "-points", california, JS(callback))
ms$get("return_data")

# explode then get centroids of all parts
ms$call("mapshaper.applyCommands", "-explode -points", california, JS(callback))
ms$get("return_data")

# rename fields then simplify
ms$call("mapshaper.applyCommands", "snap -rename-fields abbr=abbreviation -simplify 0.05", california, JS(callback))
ms$get("return_data")

# convert to lines
ms$call("mapshaper.applyCommands", "-lines", california, JS(callback))
ms$get("return_data")

# simplify then convert to lines
ms$call("mapshaper.applyCommands", "-simplify 0.05 -lines", california, JS(callback))
ms$get("return_data")

# explode then simplify, not allowing null geometries (i.e., keep all small 
# that would otherwise be simplified into non-existence)
ms$call("mapshaper.applyCommands", "-explode -simplify 0.05 keep-shapes", california, JS(callback))
ms$get("return_data")

# explode then dissolve then simplify us states
ms$call("mapshaper.applyCommands", "snap -explode -dissolve -simplify 0.05", us_states, JS(callback))
ms$get("return_data")
```
This all works really nicely! The only things I haven't been able to manage is commands that use two (or more) layers, such as `-clip` and `-erase` - the documentation only describes them by specifying a file name in the command string (`mapshaper.applyCommands` only accepts a single dataset).  I've opened an [issue](https://github.com/mbloch/mapshaper/issues/95) in the mapshaper repo to ask the question - if you have any ideas about how to do it, please chime in!

**Comment by timelyportfolio** [comment]
this is coming together very nicely!  I looked through the code and docs and don't see any way to pass `clip_poly` with `applyCommands`.  Hopefully, we'll get an answer, or might just need to do the direct route.

**Comment by ateucher** [comment]
Alright, sounds good. Incidentally, I was trying to clip with a bounding box and was getting an error `require is not defined` - evidently the mapshaper.js file I was pulling from the repo was not entirely sufficient, so I `browserified` the node module. It's hefty (800+ kb), but it fixed that problem (still needed to apply your `setTimeout` workaround though). I documented it here: https://github.com/ateucher/rmapshaper/commit/836c1d637f568407fc1a16b2d9afdb0e83220557

**Comment by timelyportfolio** [comment]
since we can't see/debug anything in `V8` anyways, we could easily just minify and get the bundle down to about 450kb.

**Comment by ateucher** [comment]
:+1:

**Comment by hrbrmstr** [comment]
Andy, doesn't `rgeos::gSimplify`'s `topologyPreserve` do what it says?

**Comment by ateucher** [comment]
Hi @hrbrmstr - not exactly. It preserves the topology of single polygons, but not multiple neighbouring polygons with shared boundaries - see [here](http://gis.stackexchange.com/questions/30782/how-to-generalize-spatialpolygons-and-conserving-topology-in-r).

**Comment by ateucher** [comment]
As suspected, `applyCommands` doesn't accept two GeoJSON files: https://github.com/mbloch/mapshaper/issues/95

So, I've probably done a Terrible Thing, and I haven't tested it nearly enough, but I have a function that does clipping using a hack with `runCommands`:

```r
library(V8)

# get a place to work
ctx <- new_context()

ctx$source('./inst/mapshaper/mapshaper-browserify.js')

poly <- '{
  "type": "FeatureCollection",
  "features": [
  {
  "type": "Feature",
  "geometry": {
  "type": "Polygon",
  "coordinates": [
  [
  [-114.345703125, 39.4369879],
  [-116.4534998, 37.18979823791],
  [-118.4534998, 38.17698709],
  [-115.345703125, 43.576878],
  [-106.611328125, 43.4529188935547],
  [-105.092834092, 46.20938402],
  [-106.66859, 39.4389646],
  [-103.6117867, 36.436756],
  [-114.34579879, 39.4361929]
  ]
  ]
  },
  "properties": {"id":"foobar"}
  }
  ]
  }'

clip_poly <- '{
"type": "Feature",
"geometry": {
"type": "Polygon",
"coordinates": [
[
  [-114, 39],
  [-114, 43],
  [-106, 43],
  [-106, 39],
  [-114, 39]
  ] ]
}
}'

mapshaper_clip <- function(target_layer, clip_layer) {
  ## Import the layers into the V8 session
  ctx$eval(paste0('var target_geojson = ', JS(target_layer)))
  ctx$eval(paste0('var clip_geojson = ', JS(clip_layer)))

  ## convert geojson to mapshaper datasets, give each layer a name which can be
  ## referred to in the commands as target and clipping layer
  ctx$eval('var target_layer = mapshaper.internal.importFileContent(target_geojson, null, {});
           target_layer.layers[0].name = "target_layer";')
  ctx$eval('var clip_layer = mapshaper.internal.importFileContent(clip_geojson, null, {});
           clip_layer.layers[0].name = "clip_layer";')

  ## Merge the datasets into one that can be passed on to runCommand
  ctx$eval('var dataset = mapshaper.internal.mergeDatasets([target_layer, clip_layer]);')

  ## Construct the command string; referring to layer names as assigned above
  command <- "-clip target=target_layer source=clip_layer -o format=geojson"

  ## Parse the commands
  ctx$eval(paste0('var command = mapshaper.internal.parseCommands("',
                  command, '")'))

  ## use runCommand to run the clipping function on the merged dataset and return
  ## it to R
  out <- ctx$get(
    "
    (function(){
      var return_data = {};
      mapshaper.runCommand(command[0], dataset, function(err,data){
        // This chunk from Mapshaper.ProcessFileContent to get output options:
        // if last command is -o, use -o options for exporting
        outCmd = command[command.length-1];
        if (outCmd && outCmd.name == 'o') {
        outOpts = command.pop().options;
        } else {
        outOpts = {};
        }
        // Convert dataset to geojson for export
        // (or if other format supplied in output options)
        return_data = mapshaper.internal.exportFileContent(data, outOpts);
      })
      return return_data;
      })()
    "
  )

  as.list(out)
}

mapshaper_clip(poly, clip_poly)
```

**Comment by timelyportfolio** [comment]
I think that is the only way, and it **works**.  I'll try to poke around and just see if I can figure out how to do a direct `clip`.

**Comment by ateucher** [comment]
Closing this now. Thanks for all your help @timelyportfolio!
