### ISSUE TITLE
Problem with callback data

### ISSUE THREAD

**Issue by masztalski** [ateucher/rmapshaper#30]
Hello,
I have strange issue when trying to convert both shp and dbf file into geojson. File *.json is generated properly, but in callback function dataset is null object, so I cannot display it
```
mapshaper.runCommands('-i shapefiles/*.shp shapefiles/*.dbf -o geojson/ format=geojson force', function(Error,dataset){
		if (Error) console.error(Error);
		console.log("data", dataset != null ? dataset : "null");
	});
```

**Comment by ateucher** [comment]
Hey there, I think you might be looking for the [mapshaper](https://github.com/mbloch/mapshaper) proper repo. This is an R package I'm developing that wraps the mapshaper library.
