### ISSUE TITLE
Simpler travis setup?

### ISSUE THREAD

**Issue by ateucher** [ateucher/rmapshaper#35]
Like here: https://github.com/jhollist/quickmapr/blob/master/.travis.yml, using trusty distro to get more recent gdal

**Comment by jhollist** [comment]
Even simpler: https://github.com/jhollist/lakemorpho/blob/master/.travis.yml

Doesn't rely on the trusty distro.

**Comment by ateucher** [comment]
Thanks! I feel like I tried that a while ago but the binary was a really old version - has it been updated?

**Comment by jhollist** [comment]
Good question.

**Comment by jhollist** [comment]
Doesn't look like it.  Line for the Travis log:

http://ppa.launchpad.net/marutter/c2d4u/ubuntu/ precise/main r-cran-rgdal amd64 0.8-16-1cran2ppa0saucy0

**Comment by ateucher** [comment]
ok, thanks for checking!
