### ISSUE TITLE
Code review?

### ISSUE THREAD

**Issue by ateucher** [ateucher/rmapshaper#4]
Hi @timelyportfolio and @sckott - I've worked out the core pieces to pass things back and forth from R and the mapshaper commands (in `test-v8` branch which I will merge into master soon), but would love a quick look before I go too much further.

I feel like the switching between `sp` classes and `json` to pass into JS-land and out again is a bit clunky, especially around projections. It's pretty nice to have `geojsonio` though - it makes it pretty easy.

I also plan to write methods for geoson list objects, so if you have any thoughts there that would be great.

**Comment by ateucher** [comment]
If you're able of course. I really appreciate the help you've given me already!

**Comment by sckott** [comment]
@ateucher will look soon

**Comment by ateucher** [comment]
Thanks @sckott - even just a quick look for any obvious pitfalls would be great.

**Comment by sckott** [comment]
Looks like there aren't egs with  the functions. Are there examples anywhere else?

**Comment by ateucher** [comment]
Ah, good point. I'll add some and ping you here again. Sorry about that

**Comment by ateucher** [comment]
Closing this for now... will likely submit to rOpenSci and hopefully get a review then :)
