### ISSUE TITLE
Support sfr

### ISSUE THREAD

**Issue by ateucher** [ateucher/rmapshaper#47]

**Comment by ateucher** [comment]
- [x] ms_simplify
- [x] ms_dissolve
- [x] ms_clip
- [x] ms_erase
- [ ] ms_explode
- [ ] ms_lines
- [ ] ms_innerlines
- [ ] ms_points
- [ ] ms_filter_fields
- [ ] ms_filter_islands

**Comment by Nowosad** [comment]
@ateucher closed?

**Comment by ateucher** [comment]
Yup, thanks! Just prepping for CRAN release...

**Comment by Nowosad** [comment]
Awesome!
