### ISSUE TITLE
launch a V8 session once per function call

### ISSUE THREAD

**Issue by ateucher** [ateucher/rmapshaper#49]
Rather than a session-wide context, launch once per function call. I think that way we should be able to support parallel processing without running out of memory as quickly.

**Comment by jbkunst** [comment]
Hi @ateucher

Yes! Please! It will be an elengant solution to https://github.com/ateucher/rmapshaper/blob/e7e0b4f3d8e67edda6bce59294c2e66ed971e90c/R/onLoad.R#L4.

Besides I have problem when I try to load the package in knitr a document. So I need to put the `library(rmapshaper)` out of the rmd document and load before knit the rmardown file :/.

Thanks for this package 💃
