### ISSUE TITLE
What about sf?

### ISSUE THREAD

**Issue by rsbivand** [ateucher/rmapshaper#51]
What about interfacing [sf?](https://cran.r-project.org/web/packages/sf/index.html)

**Comment by ateucher** [comment]
Definitely in the plan. I am working on getting sf support into [geojsonio](https://github.com/ropensci/geojsonio/pull/95) which will perform the translation to geojson (required to pass the object into the mapshaper V8 context).

**Comment by ateucher** [comment]
Duplicate of #47
