### ISSUE TITLE
Check against GRASS

### ISSUE THREAD

**Issue by rsbivand** [ateucher/rmapshaper#52]
Have you checked with a topological vector model GIS, like [GRASS](http://grass.osgeo.org/)? Are the output polygons different with [v.generalize](https://grass.osgeo.org/grass70/manuals/v.generalize.html)?

**Comment by ateucher** [comment]
I haven't, but it would be interesting to see. It doesn't look like v.generalize has the option to use the [Visvalingam](https://bost.ocks.org/mike/simplify/) simplification method, which is what [mapshaper uses](https://github.com/mbloch/mapshaper/wiki/Simplification-Tips), so I'm guessing this will cause some differences.
