### ISSUE TITLE
Large file support

### ISSUE THREAD

**Issue by Nowosad** [ateucher/rmapshaper#59]
The `mapshaper` library supports large files (https://github.com/mbloch/mapshaper) by changing the memory limit. Is it possible in `rmapshaper`?

**Comment by ateucher** [comment]
This is something I would really like to enable, but that is a feature of Node.js, not mapshaper specifically. `rmapshaper` uses the [V8](https://github.com/jeroen/V8) R package to run the mapshaper javascript library in R. Node is built on V8.

I opened an [issue](https://github.com/jeroen/V8/issues/33) about this, but it doesn't look like it's easy (certainly beyond my C++ abilities). I think it's further complicated by the fact that the V8 R package [necessarily relies on an older version of libv8](https://github.com/jeroen/V8/issues/36). Not to mention that `rmapshaper` seems to be the only use case (at least so far) that runs into these limits.

**Comment by Nowosad** [comment]
Thanks for the explanation and your great work @ateucher!
