### ISSUE TITLE
rmapshaper does not work when a column has the `units` class

### ISSUE THREAD

**Issue by Nowosad** [ateucher/rmapshaper#75]
Hi @ateucher!
The new version of **rmapshaper** has an issue that was not in the previous one.  It throws an error when at least one of the columns in the dataset has the `units` class. 
Do you think it is possible to keep this column and its class or (at least) convert it to `numeric` with a warning?

``` r
library(sf)                                                      
library(spData)                                                  
library(rmapshaper)                                              

# fails                                                                 
us_states_simp1 = rmapshaper::ms_simplify(us_states, keep = 0.01)
#> Error: No method asJSON S3 class: units

class(us_states$AREA)                                            
#> [1] "units"                                                              
us_states$AREA = as.numeric(us_states$AREA)    

# works                  
us_states_simp2 = rmapshaper::ms_simplify(us_states, keep = 0.01)
```

**Comment by ateucher** [comment]
Thanks @Nowosad! I find that a lot of functions in general don't deal well with `units` classes, so I often just end up doing as you did and converting to basic `numeric`. However, since they are pretty common in `sf` objects it is worth supporting them properly.

Related: Discussion in #69.
