### ISSUE TITLE
Warnings when simpifying sf

### ISSUE THREAD

**Issue by mtennekes** [ateucher/rmapshaper#78]
```r
library(rmapshaper)
library(spData)
library(sf)
library(sp)

world2 <- ms_simplify(world, keep=.2)
```

gives these warnings:

```
Warning messages:
1: In eval(call(as_fun, df[[n]])) : NAs introduced by coercion
2: In eval(call(as_fun, df[[n]])) : NAs introduced by coercion
3: In eval(call(as_fun, df[[n]])) : NAs introduced by coercion
```

However, the result looks ok, and also the same as sp:

```r
world_sp <- as(world, "Spatial")
world2_sp <- ms_simplify(world_sp, keep=.2)

library(tmap)
tmap_mode("view")
tmap_arrange(qtm(world_sp, title = "Original sf"), 
             qtm(world2, title = "Simplified sf"),
             qtm(world_sp, title = "Original sp"), 
             qtm(world2_sp, title = "Simplified sp"), 
             nrow = 2,
             sync = TRUE)
```

![screenshot from 2018-06-06 12-15-29](https://user-images.githubusercontent.com/2444081/41032402-9713e39a-6983-11e8-9c6c-fbc69a5b0342.png)

**Comment by ateucher** [comment]
Thanks @mtennekes. I can reproduce this. Luckily the warning is spurious - after processing with mapshaper, the original column classes are restored, and some NA's were encountered in coercion. This whole piece of rmapshaper needs reworking under the hood, as it is a bit clunky. Related to #69 and #75.

**Comment by ateucher** [comment]
Closing in favour of #69
