### ISSUE TITLE
ms_simplify changes polygon IDs

### ISSUE THREAD

**Issue by willemvdb42** [ateucher/rmapshaper#85]
The function `ms_simplify` changes the `ID` slot of the polygons when working with objects of the `spatialPolygons` or `spatialPolygonsDataFrame` classes (from the `sp` package). See reprex.

```
library(sp)
library(BelgiumMaps.StatBel) # I use this package but any package containing a spatialPolygons object will do I think.
library(rmapshaper)

data(BE_ADMIN_MUNTY) # Load the spatialPolygonsDataFrame object
simplifiedPol <- rmapshaper::ms_simplify(BE_ADMIN_MUNTY)

# Result: 
# - BE_ADMIN_MUNTY has polygon ID's starting: "1", "1_1", "1_2", etc.
# - simplifiedPol has polygon ID's "1", "2", "3", etc.
# In other words polygon ID information is lost. It is unclear if all polygons are still in the same order. 
# (I assume yes, but it's not explicitly mentioned so I cannot be sure for objects with over 1000 polygons.)
```

This causes problems for example when using the `SpatialPolygonsDataFrame` function from the `sp` package. That function takes a `spatialPolygons` object and a `data.frame` object and returns a `spatialPolygonsDataFrame` object where each row of the data.frame is matched to a polygon based on the row.name of the data.frame and the ID of the polygon. Hence with ID information lost this does not work.

Would it be possible to update the ms_simplify function so as to preserve ID information? Thanks in advance.

**Comment by ateucher** [comment]
Thanks @willemvdb42 I will look into preserving row IDs when they exist.

**Comment by rlh1994** [comment]
Just to bump this I am encountering the issue now for the first time. I only run this specific code every few months so can't be certain when the issue arose, but I used to be able to apply `ms_simplify` to a SPDF without issue, now as mentioned it leads to an error.

**Comment by ateucher** [comment]
Part of the problem with your example @willemvdb42, is that that object begins with different row.names of the data vs the polygons:

``` r
library(rmapshaper)
library(BelgiumMaps.StatBel)

data(BE_ADMIN_MUNTY)

#Overall object's row.names:
row.names(BE_ADMIN_MUNTY)[1:10]
#> Loading required package: sp
#>  [1] "1"   "1_1" "1_2" "1_3" "1_4" "1_5" "1_6" "1_7" "1_8" "1_9"

# Polygon's object's row.names:
sapply(BE_ADMIN_MUNTY@polygons, slot, "ID")[1:10]
#>  [1] "1"   "1_1" "1_2" "1_3" "1_4" "1_5" "1_6" "1_7" "1_8" "1_9"

# Data slot's row.names are different
row.names(BE_ADMIN_MUNTY@data)[1:10]
#>  [1] "11001" "11002" "11004" "11005" "11007" "11008" "11009" "11013" "11016"
#> [10] "11018"

# Make data slot's row.names match those of the polygons
row.names(BE_ADMIN_MUNTY@data) <- row.names(BE_ADMIN_MUNTY)

# works
be_simp <- ms_simplify(BE_ADMIN_MUNTY)
```

<sup>Created on 2020-06-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It's not really feasible to perfectly retain the original ID's as `ms_simplify()` can often reduce the number of polygons (by reducing them to null geometries). If you need to retain them, I would advise creating a column of them.

**Comment by ateucher** [comment]
I'm going to close this as row.names cannot be expected to be preserved in simplification, as sometimes polygons are lost (or created if using `explode=TRUE`) in the simplification process. If you need to retain them I suggest creating a column of them.
