### ISSUE TITLE
Issue: ms_simplify and sys=T not working (mapshaper version 0.4.136)

### ISSUE THREAD

**Issue by geospatial-dave** [ateucher/rmapshaper#92]
Hey mate, I've encountered a similar issue as maka in a previous issue, following up on your questions:
- File was not successfully written to location
- My user is david, definitely no special characters there

If I can help in any other way let me know, I'm trying to simplify 150MB .shp file and need to use the sys=TRUE function as it just hangs forever otherwise. Mapshaper version is 0.4.136

Error below:

```
Error: [each] Command expects a single value. Received: 'rmapshaperid = this.id'
Run mapshaper -h to view help
Cannot open data source C:\Users\david\AppData\Local\Temp\RtmpOybJjr\file281467f33312.geojson
Error in CPL_read_ogr(dsn, layer, as.character(options), quiet, type,  : 
  Open failed.
In addition: Warning message:
running command 'mapshaper C:/Users/david/AppData/Local/Temp/RtmpOybJjr/file2814188f2e0f.geojson snap -simplify 0.111  weighting=0.7 keep-shapes -each 'rmapshaperid = this.id' -o C:\Users\david\AppData\Local\Temp\RtmpOybJjr\file281467f33312.geojson' had status 1 
```

_Originally posted by @geospatial-dave in https://github.com/ateucher/rmapshaper/issues/87#issuecomment-539829589_

**Comment by geospatial-dave** [comment]
Resolved - see issue: https://github.com/ateucher/rmapshaper/issues/77

**Comment by ateucher** [comment]
Thanks @geospatial-dave - so did you have an older version of `rmapshaper` (< 0.4.1) installed?

**Comment by geospatial-dave** [comment]
that is correct, I had 0.4.0, the current live CRAN version installed originally. Using 0.4.1 developmental fixed the issue.
