### ISSUE TITLE
use runCommandsXL() when sys = TRUE and object is large

### ISSUE THREAD

**Issue by ateucher** [ateucher/rmapshaper#94]
https://github.com/mbloch/mapshaper/issues/367

**Comment by ericemc3** [comment]
excellent idea !

**Comment by ateucher** [comment]
Note: can add a new argument for memory allocation that gets passed on to `mapshaper-xl` (https://github.com/mbloch/mapshaper/blob/4a1eac2845420472bb23df863723aa8e3021ced2/README.md#large-file-support)

**Comment by ateucher** [comment]
Closed by #112
