### ISSUE TITLE
configuration failed for package 'V8'

### ISSUE THREAD

**Issue by butellyn** [ateucher/rmapshaper#98]
I tried to install rmapshaper, but it failed due to a dependency; V8. Have you run into this before? And how did you fix it? Below is the error message.
<img width="737" alt="v8error" src="https://user-images.githubusercontent.com/41019524/73015533-36d82d00-3dea-11ea-91f2-5fcd31c07500.png">

Then I tried installing with V8 with brew, which also failed (`brew install v8`):
<img width="1125" alt="v8errorbrew" src="https://user-images.githubusercontent.com/41019524/73015693-7ef74f80-3dea-11ea-912b-dbaa97128950.png">
<img width="909" alt="v8errorbrew2" src="https://user-images.githubusercontent.com/41019524/73015732-90d8f280-3dea-11ea-8623-369faf01bf0e.png">

**Comment by ateucher** [comment]
Hi @butellyn, I think the answer given in the issue you opened in the v8 repo (https://github.com/jeroen/V8/issues/82) should fix it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
