### ISSUE TITLE
apply_mapshaper_commands with sys=TRUE deletes input shp file

### ISSUE THREAD

**Issue by ericemc3** [ateucher/rmapshaper#99]
When running
apply_mapshaper_commands( "c:/apps/counties.shp", " -dissolve", sys=TRUE, force_FC=FALSE ),
counties.shp is deleted (but not counties.dbf)

**Comment by ateucher** [comment]
Thanks for reporting this @ericemc3 - I'll look into it

**Comment by ericemc3** [comment]
Thank you for your prompt action, Andy! How can i acces sthe new package (i am running rmapshapper in Windows) ?

**Comment by ateucher** [comment]
I will be submitting a new version to CRAN shortly, but in the meantime you can install the development version from GitHub using [these instructions](https://github.com/ateucher/rmapshaper#installation).

**Comment by ericemc3** [comment]
This is really great, it works fine, thank you very much! I translated a Pyqgis script into Rmapshapper and execution time was reduced from 1h to 2mn, interesting enough...

Sometimes, we just don't need that geoson automatically written on disk as result of the apply_mapshaper_commands, if we use for instance the -o command to output a shp. Could we save that 'write on disk' time with a new parameter such as WRITEJSON=TRUE/FALSE?

**Comment by ateucher** [comment]
If you're not using it within a broader R-based workflow, you can just use the `mapshaper` command-line tool directly: https://github.com/mbloch/mapshaper/wiki/Introduction-to-the-Command-Line-Tool

**Comment by ericemc3** [comment]
yes of course, but i am indeed using a broader R-based workflow with dplyr and soon rshiny
